### ISSUE TITLE
Home Users

### ISSUE THREAD

**Issue by EMBoots** [aunefyren/wrapperr#101]
When running Wrapperr it obviously makes you sign in with your Plex account. However, I have a few people on the same Plex account via the Home Users platform.
This syncs with Tautulli as expected however there doesn't seem to be a way to sign in or get your Wrapped as a home user.
If this isn't a feature already, is there a timeline for when that may be a thing?

Thank you :)

**Comment by EMBoots** [comment]
I'm an idiot and found the Plex Auth button after trying to change it in the docker container 🤦

**Comment by aunefyren** [comment]
No worries, glad you found it
