### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by aaagtron** [aunefyren/wrapperr#103]
Trying to connect Tautulli and Wrapper and I keep getting this message:

```
Failed to connect to Tautulli server. 

Reply: <!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>404 Not Found</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>404 Not Found</h2>
        <p>The path '/home:8181/api/v2/' was not found.</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.dev">CherryPy unknown</a>
      </span>
    </div>
    </body>
</html>
. 

Error: Tautulli didn't respond with status code 200, got: 404 Not Found instead.
```

**Comment by aunefyren** [comment]
Seems it can't reach the Tautulli server. What is your setup like?

**Comment by Fma15** [comment]
I have the exact same error. Tautulli, plex, and wrapperr are all on the same computer running windows 10. I don't have docker either. If you need anymore info let me know.

**Comment by wbshaw** [comment]
What have you set the path to tautulli as in wrapper, and have you checked that it works in a browser?

**Comment by aunefyren** [comment]
> path '/home:8181/api/

Seems like either your Tautulli config is wrong or Wrapperr is appending the port in the wrong place. Can you share your configuration with redacted information?

**Comment by Fma15** [comment]
this is my setup.

https://ibb.co/0Yp14HH

My server name is just the username I use to log into Tautulli.

**Comment by wbshaw** [comment]
> this is my setup.
> 
> https://ibb.co/0Yp14HH
> 
> My server name is just the username I use to log into Tautulli.

Just put the IP address in the tautulli connection field, e.g. 192.168.x.x 
You don't need http:// or the port for that field. Port number goes in the port field, which looks correct.

**Comment by aunefyren** [comment]
Seems like you have /tautulli/home in your Tautulli path, so you must add that as a URL Base. It is within your Tautulli config on Wrapperr.

**Comment by Fma15** [comment]
@wbshaw 

I changed it to match yours (I of course used my own ip). I still got the same error though

@aunefyren 

So I should just add /tautulli/home as my URL Base? I also didn't change the default base in Tautulli

**Comment by wbshaw** [comment]
> @wbshaw
> 
> I changed it to match yours (I of course used my own ip). I still got the same error though
> 
> @aunefyren
> 
> So I should just add /tautulli/home as my URL Base? I also didn't change the default base in Tautulli

If you haven't changed the default in Tautulli then just leave the 'IP or domain for tautulli ' field as just the IP, nothing else, and leave the base URL field empty. 

The original log shows it falls as it's trying to connect to /home which doesn't exist.

**Comment by aunefyren** [comment]
@Fma15, based on your provided information you need something like this:

![image](https://github.com/user-attachments/assets/266a07f2-af86-46b9-9fab-503db803fa4e)

**Comment by Fma15** [comment]
Thanks a million! it works now!
