### ISSUE TITLE
Can't seem to connect

### ISSUE THREAD

**Issue by Sietsevdm** [aunefyren/wrapperr#107]
Im trying to setup Wrapper but i keep getting this message.
My tautulli isn't hosted by me and is on a external network.

```
2024/12/22 22:09:55 Failed to connect to Tautulli server.

Reply: <!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>404 Not Found</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>404 Not Found</h2>
        <p>The path '/home:8181/api/v2/' was not found.</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.dev">CherryPy unknown</a>
      </span>
    </div>
    </body>
</html>
. +n
Error: Tautulli didn't respond with status code 200, got: 404 Not Found instead.
[GIN] 2024/12/22 - 22:09:55 | 500 |    133.7816ms |             ::1 | POST     "/api/get/tautulli-connection"
```

This is my setup, i also tried port 8181 but no luck
![image](https://github.com/user-attachments/assets/d9ade71b-a996-4d34-bdf9-df89e299246d)

**Comment by wbshaw** [comment]
> Im trying to setup Wrapper but i keep getting this message. My tautulli isn't hosted by me and is on a external network.
> 
> ```
> 2024/12/22 22:09:55 Failed to connect to Tautulli server.
> 
> Reply: <!DOCTYPE html PUBLIC
> "-//W3C//DTD XHTML 1.0 Transitional//EN"
> "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
> <html>
> <head>
>     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
>     <title>404 Not Found</title>
>     <style type="text/css">
>     #powered_by {
>         margin-top: 20px;
>         border-top: 2px solid black;
>         font-style: italic;
>     }
> 
>     #traceback {
>         color: red;
>     }
>     </style>
> </head>
>     <body>
>         <h2>404 Not Found</h2>
>         <p>The path '/home:8181/api/v2/' was not found.</p>
>         <pre id="traceback"></pre>
>     <div id="powered_by">
>       <span>
>         Powered by <a href="http://www.cherrypy.dev">CherryPy unknown</a>
>       </span>
>     </div>
>     </body>
> </html>
> . +n
> Error: Tautulli didn't respond with status code 200, got: 404 Not Found instead.
> [GIN] 2024/12/22 - 22:09:55 | 500 |    133.7816ms |             ::1 | POST     "/api/get/tautulli-connection"
> ```
> 
> This is my setup, i also tried port 8181 but no luck ![image](https://private-user-images.githubusercontent.com/31568491/398013044-d9ade71b-a996-4d34-bdf9-df89e299246d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MDI1MzMsIm5iZiI6MTczNDkwMjIzMywicGF0aCI6Ii8zMTU2ODQ5MS8zOTgwMTMwNDQtZDlhZGU3MWItYTk5Ni00ZDM0LWJkZjktZGY4OWUyOTkyNDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDIxMTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMzNmZmQyZjk3ODYzNGI5ZjkzNDhmOTQzMTg2OGUzYjY0MzMyY2E3OTdlMjdiNDI0YTBkNTgxMzJjZDYwZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4ESdkK5ksNSapobm2RVBeTpWS2UoabXe5B5wcJUeFow)

Try the domain without the HTTPS:// part.

**Comment by Sietsevdm** [comment]
@wbshaw same result with both 80 and 8181 :(

**Comment by wbshaw** [comment]
@Sietsevdm that's with the HTTPS:// part of the URL removed? Do you have anything at the end of the URL after the /?  If so remove that as well. 

The initial error log you posted suggests that it's trying to contact tautulli on Https://home/, does it look any different this time?

**Comment by Sietsevdm** [comment]
@wbshaw well damn that got me a bit further
![image](https://github.com/user-attachments/assets/01daa91d-7092-48e6-af85-0cc768916270)

**Comment by wbshaw** [comment]
@Sietsevdm check the tautulli logs and see if that helps? Assume you have 'enable api' turned on in tautulli?

**Comment by aunefyren** [comment]
Is your Tautulli hosted on a subfolder like /home?

**Comment by Sietsevdm** [comment]
@wbshaw Enable API is turned on, and the HTTP port is set to 8181
@aunefyren im not sure how to check this since i don't host it myself, anyway i can find out?

Also the logs don't show anything, the last API log message is from hours ago
![image](https://github.com/user-attachments/assets/8b1de79e-b0a4-4482-8c96-eea6e81a7608)

**Comment by wbshaw** [comment]
@Sietsevdm cool, so it's port mapped from 8181 external to 8181 internal? When you connect to tautulli in the browser you're using HTTPS//[public-URL]:8181 yes?

**Comment by aunefyren** [comment]
When you access Tautulli, is there anything needed in the URL after the domain to specifically reach the Tautulli service? That would be configured in Wrapper as a Tautulli URL Base.

For instance, if you reach Tautulli at http://192.168.1.1/tautulli, then /tautulli is the URL Base.

**Comment by Sietsevdm** [comment]
@aunefyren no its just this, 
![image](https://github.com/user-attachments/assets/aef0c60a-aae2-4363-8387-a9383a73d171)

 @wbshaw this also answers your question i think

**Comment by wbshaw** [comment]
Ok, so port 80 it should be, or 443... @aunefyren can confirm how SSL is handled when you check the SSL box.

**Comment by Sietsevdm** [comment]
@wbshaw i'll be damned, that did the trick!

**Comment by wbshaw** [comment]
Which did you use, 443 or 80?

**Comment by Sietsevdm** [comment]
I used 443 :)

Thanks for the quick support!

**Comment by aunefyren** [comment]
> Ok, so port 80 it should be, or 443... @aunefyren can confirm how SSL is handled when you check the SSL box.

The HTTPS box changes the protocol from HTTP to HTTPS
The port is indepentdent from this, as you techically can host HTTPS on port 80, its just not the norm.
Typically when doing HTTPS you want port 443, yes.
