### ISSUE TITLE
Option to adjust data pulled from Tautulli

### ISSUE THREAD

**Issue by ctrlaltd1337ed** [aunefyren/wrapperr#19]
Hey there, love this project! Lots of fun to share this data with friends and family.

One thing I was wondering was if it was possible to change which data is pulled for "top movies." Currently, it is pulling from `Play Duration`, and not `Play Count`.

For example, Justice League (14 plays) was my "top movie" according to this project, because it pulls amount of time watched for the leaderboard. When really, Black Widow (21 plays) should be the "winner" as it was played more, but Justice League was a much longer movie.

Might be too late into the year to make it a consideration, just thought it was something to bring up and see if it was just me that would like the option.

**Comment by aunefyren** [comment]
That is a great idea and totally something I am planning on adding! :)

**Comment by aunefyren** [comment]
Added in v2.2.0
