### ISSUE TITLE
Option to change header text in each section

### ISSUE THREAD

**Issue by ponchohoncho** [aunefyren/wrapperr#21]
I love the new changes! I am glad to have the ability to turn off buddies and leaderboards, but the server-wide stats have a header that's hard coded to reference seeing usernames on a list ("It's okay to feel shame if you are on the list.") and it would be nice to be able to change that text. Tokenizing the text would also make translation possible!

**Comment by aunefyren** [comment]
Great point. More custom text is definitely a good idea!

**Comment by aunefyren** [comment]
Added in v2.2.0
