### ISSUE TITLE
Mobile Client Not Working

### ISSUE THREAD

**Issue by 14wkinnersley** [aunefyren/wrapperr#23]
Issue: When accessing the application from a mobile client, after clicking 'Sign in using Plex' it gets stuck at a 'Loading...' and never asks for plex login.

Using Docker installed via Unraid.

**Comment by aunefyren** [comment]
There is a pop up login window that should open when clicking 'Sign in using Plex'. Does this not open? Could it be related to browser settings blocking pop up.

**Comment by 14wkinnersley** [comment]
That was it, My apologies. Never had that happen on other apps that use plex auth.

**Comment by aunefyren** [comment]
No worries
