### ISSUE TITLE
[Issue] After caching, nothing shows when pressing "Unwrap"

### ISSUE THREAD

**Issue by VP-EN** [aunefyren/wrapperr#28]
**[Issue] After caching, nothing shows when pressing "Unwrap"**

**Describe the bug**
When I press "unwrap" after updating to the latest version of wrapperr, nothing appears.
After cloning the most recent version, creating a new admin password, setting up Tautulli, and creating the cache, nothing appears after logging in and pressing "Unwrap."
It only displays the "new year, new statistics" page, followed by the "goodbye, stay safe" page, with no statistics.
This was not the case in the previous edition, so I'm not sure what happened.
I deleted the entire contents of the previous folder, before "upgrading" to the new version. Reproducing steps below (atleast for me)..

**To Reproduce**
1. Create a quick domain-setup, with `/etc/nginx/sites-enabled/wrapped.domain.com.conf` and enable PHP.
2. The `wrapped.domain.com.conf` file looks like [this](https://0bin.net/paste/SqoA+bsp#o32rGMWyTZQm21Wl8aR5YGhOjSO38RH0dI4-OXY1fy9)
3. `cd /var/www/wrapped.domain.com`
4. `sudo git clone https://github.com/aunefyren/wrapperr.git`
5. `sudo chown -R www-data:www-data wrapperr/`
6. `sudo chmod -R 0777 /var/www/wrapped.domain.com/wrapperr/config`
7. I configured an admin login/password
8. I configured my Tautulli and confirmed it is working (green Test Connection prompt)
9. I chose the pre-cache option, 50 days
10. Waited for the cache to complete
11. Confirmed that the `cache.json` file in `/var/www/wrapped.domain.com/wrapperr/config` was created (size is about 5-6mb after pre-cache)
12. Restarting nginx, `sudo service nginx restart`
13. Login using the "Sign in using Plex" prompt
14. After logging in, I press "Unwrap", and it shows no stats. Only the welcome and goodbye page(s).
15. Be sad: https://i.imgur.com/7FaNrXm.png

**Expected behavior**
It should work like last time 🥲 

**Operating System**
Ubuntu 21.10

**Comment by aunefyren** [comment]
Could it be the different stat-options on the 'Wrapperr customization' admin page are disabled? Everything is disabled by default. I feel I should either change that or make it clear in the documentation.

**Comment by VP-EN** [comment]
Haha wow, that's exactly it. Now it works, sorry about that lol
