### ISSUE TITLE
Not getting any server-wide statistics when user has zero plays

### ISSUE THREAD

**Issue by ctrlaltd1337ed** [aunefyren/wrapperr#30]
I have an "admin account" for Plex where I log in and do everything on the server, and then I made a secondary account for viewing.

When logging into Wrapperr via Plex sign-on on my admin account, the only thing I get in the wrap up is "you watched zero movies," "you watched zero TV shows."

Tried it with the secondary account and it works fine.

**Comment by aunefyren** [comment]
> When logging into Wrapperr via Plex sign-on on my admin account, the only thing I get in the wrap up is "you watched zero movies," "you watched zero TV shows."

Sounds correct if you don't watch anything on that account. Is the issue what is mentioned in the title, that server-wide is wrong when personal stats are empty?

**Comment by ctrlaltd1337ed** [comment]
Yeah, I definitely left out key info there - my bad.

That's all I see. It says zero movies and zero shows, and doesn't show me anything else. No server-wide stats at all.

**Comment by aunefyren** [comment]
I see, thank you. I'll have a look.

**Comment by aunefyren** [comment]
> Yeah, I definitely left out key info there - my bad.
> 
> That's all I see. It says zero movies and zero shows, and doesn't show me anything else. No server-wide stats at all.

I think this issue was related to a bug that crashed JavaScript, so the server-wide stats and outro didn't get to load. Others also had this issue. Are you able to upgrade to v2.2.4 and check if the issue persists?

**Comment by ctrlaltd1337ed** [comment]
Confirmed that even though my "admin account" has zero plays, I can now see all server statistics.

Thanks!
