### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by nofences** [aunefyren/wrapperr#33]
I manage 6 servers located in various locations and would love to have a single webpage to view stats from all of them. I have tautulli running on each server and would love a central place to aggregate the stats.

**Comment by aunefyren** [comment]
That could be cool, and it is definitely possible. I'll look into how difficult this would be to implement.

**Comment by shutchi2** [comment]
This would be awesome, just discovered this today and I have multiple servers that I would love to be able to compile their stats for my users. Software looks great btw.

**Comment by aunefyren** [comment]
Added in v3.1.0 😁
