### ISSUE TITLE
Not working after update to Unraid 10.6.2

### ISSUE THREAD

**Issue by thorrrr** [aunefyren/wrapperr#34]
Not working after update to Unraid 10.6.2 it keeps saying not configured.  BUt i can see all the files and the config id full filled out with all the info???

![image](https://user-images.githubusercontent.com/8170673/173068419-0781ba45-bd2d-42bf-95df-ab94fe901095.png)

![image](https://user-images.githubusercontent.com/8170673/173068520-dbb24af9-8be2-4051-895a-f061ec9a5e5f.png)

![image](https://user-images.githubusercontent.com/8170673/173068639-c4f4ffc1-7623-497f-b865-9e6585282309.png)

**Comment by thorrrr** [comment]
Permissions look ok 

![image](https://user-images.githubusercontent.com/8170673/173179993-42c368b1-2435-4a69-bd3f-268cef202250.png)

**Comment by aunefyren** [comment]
Ahh, that makes sense. Wrapperr doesn't consider itself configured if there is no admin account. Feel free to reopen this if you have any more issues.
