### ISSUE TITLE
Cannot configure wrapper on Docker, http://localhost/admin just has title "Wrapper Setup" and "Wrapper | Admin | Github" at bottom with nothing in between

### ISSUE THREAD

**Issue by MikeRotch76** [aunefyren/wrapperr#35]
I haven't used Wrapper in a while, the last time I succesfully logged in and checked stats was probably back in Feb.  However, recently, I tried to log in and couldn't, so I removed the Wrapper container, then image, then redownloaded and tried to launch Wrapper by running the command I've always used:

docker run -p '12380:80' --name 'wrapperr' --restart unless-stopped aunefyren/wrapperr:latest 

When I go to http://localhost:12380/admin, except for the title and the links at the bottom, the page is blank.  I have tried  4 different browsers (FF, Chrome, Edge, Vivaldi) and they all display the same.  I have tried clearing all cookies and cache, I have tried restarting Docker.
I went into /config and saw that both admin.json and config.json have 0 bytes.  Is that normal?

![Screenshot 2022-07-04 110406](https://user-images.githubusercontent.com/70385220/177196258-1da92bea-2efa-4c28-85c5-2e3d5c9979c1.png)

**Comment by aunefyren** [comment]
Wrapperr, including the Docker image, just got a much-needed update. Can you try v3.0.0 and see if you still have issues?

**Comment by MikeRotch76** [comment]
Sorry to report.  I just updated Docker to the latest version and still the same thing.

**Comment by aunefyren** [comment]
Did you change the port on Wrapper from 8282, or direct the new Docker traffic accordingly?

**Comment by MikeRotch76** [comment]
I've tried 8282, 12380, 80 for ports.  All have the same behaviour.  I've even spun up a new client for every attempt VM just so I can use a browser/machine that has never connected to that container before and same result.

**Comment by aunefyren** [comment]
`docker run -p '80:8282' --name 'wrapperr' --restart unless-stopped aunefyren/wrapperr:latest`

Something like this?

Anything in the browser console?

**Comment by MikeRotch76** [comment]
Yep.
docker run -p '8282:80' --name 'wrapperr' --restart unless-stopped -aunefyren/wrapperr:latest 
docker run -p '12380:80' --name 'wrapperr' --restart unless-stopped -aunefyren/wrapperr:latest 
docker run --name 'wrapperr' --restart unless-stopped -aunefyren/wrapperr:latest

**Comment by aunefyren** [comment]
It's running on 8282 internally (right side of "-p <port>:<port>") unless you changed it manually. Try my example

**Comment by MikeRotch76** [comment]
sorry, working on Console logs

**Comment by MikeRotch76** [comment]
So after I updated my Docker, I pulled the latest image of Wrapper and I ran this command:
docker run -d -p '80:8282' --name 'wrapperr' --restart unless-stopped aunefyren/wrapperr:latest 
Now the admin page looks like this
![Screenshot 2022-07-04 154150](https://user-images.githubusercontent.com/70385220/177218859-2339d236-bd34-453f-bc26-2f7b0b13e002.png)

**Comment by MikeRotch76** [comment]
The console just shows this:
___       __    ________   ________   ________   ________   _______    ________   ________     
|\  \     |\  \ |\   __  \ |\   __  \ |\   __  \ |\   __  \ |\  ___ \  |\   __  \ |\   __  \    
\ \  \    \ \  \\ \  \|\  \\ \  \|\  \\ \  \|\  \\ \  \|\  \\ \   __/| \ \  \|\  \\ \  \|\  \   
 \ \  \  __\ \  \\ \   _  _\\ \   __  \\ \   ____\\ \   ____\\ \  \_|/__\ \   _  _\\ \   _  _\  
  \ \  \|\__\_\  \\ \  \\  \|\ \  \ \  \\ \  \___| \ \  \___| \ \  \_|\ \\ \  \\  \|\ \  \\  \| 
   \ \____________\\ \__\\ _\ \ \__\ \__\\ \__\     \ \__\     \ \_______\\ \__\\ _\ \ \__\\ _\ 
    \|____________| \|__|\|__| \|__|\|__| \|__|      \|__|      \|_______| \|__|\|__| \|__|\|__|
 ____________   ____________   ____________   ____________   ____________   ____________   ____________  
|\____________\|\____________\|\____________\|\____________\|\____________\|\____________\|\____________\
\|____________|\|____________|\|____________|\|____________|\|____________|\|____________|\|____________|

Starting Wrapperr on port: 8282.

 ___       __    ________   ________   ________   ________   _______    ________   ________     
2022/07/04 21:37:46 Config file does not exist. Creating.
|\  \     |\  \ |\   __  \ |\   __  \ |\   __  \ |\   __  \ |\  ___ \  |\   __  \ |\   __  \    
\ \  \    \ \  \\ \  \|\  \\ \  \|\  \\ \  \|\  \\ \  \|\  \\ \   __/| \ \  \|\  \\ \  \|\  \   
 \ \  \  __\ \  \\ \   _  _\\ \   __  \\ \   ____\\ \   ____\\ \  \_|/__\ \   _  _\\ \   _  _\  
  \ \  \|\__\_\  \\ \  \\  \|\ \  \ \  \\ \  \___| \ \  \___| \ \  \_|\ \\ \  \\  \|\ \  \\  \| 
   \ \____________\\ \__\\ _\ \ \__\ \__\\ \__\     \ \__\     \ \_______\\ \__\\ _\ \ \__\\ _\ 
    \|____________| \|__|\|__| \|__|\|__| \|__|      \|__|      \|_______| \|__|\|__| \|__|\|__|
 ____________   ____________   ____________   ____________   ____________   ____________   ____________  
|\____________\|\____________\|\____________\|\____________\|\____________\|\____________\|\____________\
\|____________|\|____________|\|____________|\|____________|\|____________|\|____________|\|____________|

Starting Wrapperr on port: 8282.

**Comment by aunefyren** [comment]
Ahh, yes, based on the color that is the newest build. Doesn't seem like the front end can reach the API. 

Can you see if your we browser console says anything about it?

You open the Firefox Web Console from a menu or with a keyboard shortcut:
- Choose Web Console from the Web Developer submenu in the Firefox Menu (or Tools menu if you display the menu bar or are on Mac OS X)
- Or, Press the Ctrl + Shift + K (Cmd + Opt + K on OS X) keyboard shortcut.

**Comment by aunefyren** [comment]
Thank you.

Is the front-end (your browser) separated from the Internet? `https://code.jquery.com/jquery-3.2.1.min.js` doesn't resolve in your browser, and that code is necessary for the site to function.

**Comment by aunefyren** [comment]
No problem, glad you got it to work. `jquery` will actually be phased out in the future if that helps ;)
