### ISSUE TITLE
Cache not working

### ISSUE THREAD

**Issue by lucdg** [aunefyren/wrapperr#36]
I just upgraded to release v3.0.1 but i'm having an issue with the cache. I've run a manual cache update but when I unwrap it states in the log "No Wrapperr links found for" my username. It then recaches and display results but if I then immediately return and unwrap again it shows the same message in the log and recaches again. I've attached the relevent section from the logs. Any idea what I got wrong? Thanks
[log.txt](https://github.com/aunefyren/wrapperr/files/9045162/log.txt)

**Comment by aunefyren** [comment]
The v3.0.1 update made a change which, in my testing at least, fixed the 'cache-download-loop', but it looks like that is what you are experiencing. Could you attempt to restart the application? Seems like you are using Docker, so `docker restart <container-name>` should do the trick.

**Comment by lucdg** [comment]
Thanks for the response but it doesn't seem to have helped. I restarted the docker but it made no difference. Still recaching each time. I did notice at the bottom of the wrapperr page it shows v3.0.0. I deleted my docker image and referenced tag v3.0.1 directly but still shows v3.0.0 on the wrapperr page. Have I got the latest update?

**Comment by aunefyren** [comment]
Just remembered I forgot to change the version name on the new release, so it displays v3.0.0 still 😅

But what exactly happens when you try to generate statistics. Does it load anything, or does it loop forever?
Also, what is your Docker run command/Docker-Compose file?

**Comment by aunefyren** [comment]
> That's why i dropped the date range to just a week while working on this issue

Ahh, that makes sense. I guess all the data is refreshed, which is not the looping issue.

I take `Cache results for later use:` is enabled in the `Wrapperr settings`? Is there a file named cache.json in your config directory? Any content in the file?

**Comment by lucdg** [comment]
Correct Cache results for later use: is enabled. I've attached my config below. The cache.json is there and it is being used. Looking at it each unwrap it's actually adding the same data in the cache each time just below the last run. Its growing larger each time. Thanks for helping!
[config.txt](https://github.com/aunefyren/wrapperr/files/9046037/config.txt)
.

**Comment by lucdg** [comment]
That did it! Working perfectly now. Thanks for all your help. Love the project.

**Comment by aunefyren** [comment]
> That did it! Working perfectly now. Thanks for all your help. Love the project.

Thank you ❤️

By being so available and responsive you are helping me improve this project!
