### ISSUE TITLE
Can't set timezone in setup

### ISSUE THREAD

**Issue by pressRtowin** [aunefyren/wrapperr#37]
Every attempt to save the wrapperr config results in an error that reads "Given time zone is invalid." I've tried multiple different zones with no luck.

**Comment by aunefyren** [comment]
That seems odd. Can you give me some examples of time zones you are trying? Also, are you able to change other settings at all?

**Comment by pressRtowin** [comment]
I was able to continue setup by typing the timezone directly into the config.json. Not sure if it'll work.

I tried various ones like America/Chicago, as well as the given example of Europe/Oslo. They all resulted in the same error.

**Comment by aunefyren** [comment]
Does the wrapperr.log file in the config directory say anything in relation to this?

**Comment by pressRtowin** [comment]
2022/07/21 17:24:14 Failed to set the new time zone. Error: 
2022/07/21 17:24:14 The system cannot find the path specified.
2022/07/21 17:24:14 Returned error: 'Given time zone is invalid.' - Origin: [::1]:55191

for each time I attempted to save

**Comment by aunefyren** [comment]
Ahh, I see. I should make the log message say what time zone it failed to set because I am guessing your input didn't arrive the way you wrote it.

If you set the time zone in the JSON file manually, does the application start up properly with that time zone intact?

**Comment by pressRtowin** [comment]
I typed "America/Chicago" into the JSON and the same appeared in the text field of the config page after a refresh, however, after quitting and restarting the application, I get this: 
![image](https://user-images.githubusercontent.com/25999169/180328683-fedc4cb5-fb39-4a91-8554-6e722e39abe6.png)

**Comment by pressRtowin** [comment]
Didn't mention it before, but for the sake of having all the information here, I'm on windows 10.

**Comment by aunefyren** [comment]
Thank you for your help, this turned out to be a Windows issue. Fixed in v3.0.3 :)
