### ISSUE TITLE
Connecting to gui/setup on port 8282

### ISSUE THREAD

**Issue by ConnorEMacLean** [aunefyren/wrapperr#38]
Greetings!

Thanks in advanced for any assistance/the awesome app!

Attempting to install and run within Docker running on Unraid. I have installed the wrapperr docker container and left everything defaulted as those ports are free on my system.

The container runs and checking the log see it states no config found creating config and wrapperr is started on port 8282.
However navigating to localip:8282 can't seem to connect.
I've confirmed no other contain is using 580 or port 8282 but can't seem to connect  or pull up /admin.

I did look in the /appdata location as well and see no config files are being created. 

Thanks again and apologizes for what might be a basic question! 

-Cheers

**Comment by aunefyren** [comment]
I'm unfamiliar with unRAID so unsure what the issue is. Is there a Docker run command or Docker Compose config you can share?

**Comment by ConnorEMacLean** [comment]
It's installed via the Community App manager, I'm very green to all this so I know there are Docker commands but in this case I just installed via the app manager and filled in the settings asked. I've attached a screenshot below of this as well as log out put I see. I also tested adjust in the docker app setup the Web UI port from the 580 the template comes with to 8282 to no avail. 

In the video I watched on the initial setup it was suggested that the wrapperr directory within appdata have full w/r permissions which I've confirmed as well. 

Link to the video: https://youtu.be/4OHnZt9cbhw?t=649

Thanks, 
![Docker](https://user-images.githubusercontent.com/47136415/187266407-ec9932e8-83f9-4bfa-a950-eeb38ef005b4.PNG)
![Logz](https://user-images.githubusercontent.com/47136415/187266412-b06a154f-03f7-4b9e-a0e9-a0b6cd65c3b9.PNG)

**Comment by ConnorEMacLean** [comment]
I'd be also more than happy to install it via docker commands however was unsure how to map it properly to my Docker proxy network which all my other containers run on. Apologizes again for the lack of knowledge here!

**Comment by aunefyren** [comment]
> It's installed via the Community App manager, I'm very green to all this so I know there are Docker commands but in this case I just installed via the app manager and filled in the settings asked. I've attached a screenshot below of this as well as log out put I see. I also tested adjust in the docker app setup the Web UI port from the 580 the template comes with to 8282 to no avail.
> 
> In the video I watched on the initial setup it was suggested that the wrapperr directory within appdata have full w/r permissions which I've confirmed as well.
> 
> Link to the video: https://youtu.be/4OHnZt9cbhw?t=649
> 
> Thanks,
> 
> ![Docker](https://user-images.githubusercontent.com/47136415/187266977-faf0c1ca-04da-4402-afa6-0a0481a4ed25.PNG) ![Logz](https://user-images.githubusercontent.com/47136415/187266979-dfc2ab75-c2c3-4d3d-a005-36b9f5793e0d.PNG)

Woah, didn't know someone made a tutorial, that's awesome! Unfortunately the application backend has been remade so it doesn't really apply any more.

The screenshot has some values in yellow text, which I presume is the values it thinks Wrapperr is using. The port is not 80 by default any more, it's 8282. The container path is also `/app/`, meaning the config directory is `/app/config`

**Comment by ConnorEMacLean** [comment]
Thanks the mention of ports got me looking in there. I removed that current WebUI value that was mapped and create a new one mapping container and host port to 8282 and now I'm able to reach the site/admin console. 

Thanks for the assistance in helping narrowing this down/resolving!

**Comment by aunefyren** [comment]
No worries, happy to help 😁

**Comment by UsefulJeroen** [comment]
Yeah it seems like the CA default template has an incorrectly specified web ui port

**Comment by aunefyren** [comment]
> Yeah it seems like the CA default template has an incorrectly specified web ui port

Hi, is this related to unRaid community applications? I noticed the template was misconfigured based on feedback, but I found no way to update it myself. I am a bit unfamiliar with the concept and did not create the CA myself, someone else did. Would love to find a way to maintain it so please tell me if you know how I can do this.

**Comment by ctrlaltd1337ed** [comment]
> 

You can check out the team who did this at IBRACORP Discord: https://discord.gg/ibracorp-595508571135803403

I've attempted to have them change this, but it doesn't seem like they've changed it.

**Comment by ctrlaltd1337ed** [comment]
@aunefyren 

You can check out the team who did this at IBRACORP Discord: https://discord.gg/ibracorp-595508571135803403

I've attempted to have them change this, but it doesn't seem like they've changed it.

**Comment by MountainGod2** [comment]
@aunefyren they are simply .xml files hosted on github which Unraid translates into the appropriate docker run command. The current location for this project's template is here: https://github.com/ibracorp/unraid-templates/tree/master/wrapperr

I've gone ahead and updated the aforementioned template (see above PR), so once it syncs to community apps, I believe this issue could likely be closed.

**Comment by ctrlaltd1337ed** [comment]
@MountainGod2 / @aunefyren can you confirm it is `/app/config` and not `/var/www/html/app/config`? My config has reset itself 4 times since update 3.1.0 and I don't feel like doing it again after I re-install with new paths ahah.

**Comment by aunefyren** [comment]
> @MountainGod2 / @aunefyren can you confirm it is `/app/config` and not `/var/www/html/app/config`? My config has reset itself 4 times since update 3.1.0 and I don't feel like doing it again after I re-install with new paths ahah.
> 
> My current setup:
> 
> Container path: /var/www/html/app/config Host path: _my appdata directory_
> 
> Container port: 8282 Host port: _port I chose_

It has been /app/config since v3.0.0. The newest release (v3.1.0) automigrates from the previous configuration and now it also keeps a backup of the old one if it has to replace it.
