### ISSUE TITLE
Feature Request for server rankings

### ISSUE THREAD

**Issue by ascheel319** [aunefyren/wrapperr#39]
I was hoping that you add the number of plays or time spent watching on the leader board. It could show how close or far everyone was away from each other.

**Comment by aunefyren** [comment]
This was initially avoided for privacy reasons, but now I feel this could be added with an option to disable for those concerned. Good idea! :)

**Comment by aunefyren** [comment]
Added in v3.0.4. Feel free to re-open if necessary.
