### ISSUE TITLE
Results not showing up for any date range

### ISSUE THREAD

**Issue by scottruzal** [aunefyren/wrapperr#40]
Hi, 

I've been trying to get 2022 statistics to show up on the wrapped results page. The Tautulli connection is successful, I've changed the date range in the Wrapperr settings, cleared the cache and re-cached the Tautulli data several times, but nothing appears to be working.

Here is what the results page looks like when trying to view the wrapped page:

![image](https://user-images.githubusercontent.com/8886427/192001650-470ca9f8-aba5-4224-8290-9b38494fd18e.png)

Any help you can provide would be greatly appreciated!

Thanks

**Comment by aunefyren** [comment]
Hi, thanks for reaching out! I have a few questions.

If you save new settings do they retain when you refresh the admin page?
Do you have any/all statistics enabled on the 'Wrapperr customization' page?
Anything in the log after loading statistics?

**Comment by scottruzal** [comment]
Thanks for the quick response! Apologies for not looking at this more closely, but when I checked the Wrapperr customization settings I found all of the "Get ... statistics" checkboxes were all unchecked.

After checking all the boxes, everything is working great. Thanks again for all of your hard work.

**Comment by aunefyren** [comment]
> Thanks for the quick response! Apologies for not looking at this more closely, but when I checked the Wrapperr customization settings I found all of the "Get ... statistics" checkboxes were all unchecked.
> 
> After checking all the boxes, everything is working great. Thanks again for all of your hard work.

Happy to help! 👍
