### ISSUE TITLE
Annual summary for Audio Books

### ISSUE THREAD

**Issue by DoomTroopa84** [aunefyren/wrapperr#41]
Hey sorry I am fairly amateurish to this but I am trying to create an end of year summary for my user of all the audiobooks they have listened too over the year. Wrapper pulls the top 10 but I really need the whole list, ideally I could include the labum art like I do for the newsletter and a synopsis from the plex database. Then send this out as a newsletter, or at least let me generate urls that I can send out.

Any help appreciated.

Also I tried to use {album_count}  for total albums played but didn't work, is there a list of tags?

**Comment by aunefyren** [comment]
Hey, thanks for trying out Wrapperr! 

- Allowing users to see more than the top 10 is something I can implement as a Wrapperr Customization feature, so thank you for the suggestion.
- Posters/art is a good idea, and already suggested (#12), but I need a good way to implement them into the front end. I'll take some time to decide where to pull the assets from and how to display them correctly. The general look and mobile-friendly UI need to be preserved. 
- Newsletter/e-mail integration has also been suggested (#6), and could be a great addition to the project. This could take some time to do correctly, but as you mentioned, creating URLs for users is an alternative. Most of this functionality is already implemented so it could function as a placeholder. 
- I'll take a look at the tag you mentioned and make sure it functions as it should. They were created quite quickly and should absolutely be documented properly. 

Thank you for your suggestions and feel free to ask if I can help with anything.

**Comment by DoomTroopa84** [comment]
Hey thanks for the quick reply. The album art is uploaded to a server when newsletters are generated by plex, some free hosting thing i cant recall. Thats just a nice to have anyway. What i really need is all albums between the date ranges. My friends and i like to do annual reading/listening lists.

Regards,

Richard
________________________________

**Comment by aunefyren** [comment]
Added in v3.0.4. Feel free to re-open if necessary.

**Comment by DoomTroopa84** [comment]
Hey mate, thanks for implementing, but how do I set the number of albums?

**Comment by aunefyren** [comment]
> Hey mate, thanks for implementing, but how do I set the number of albums?

If you head to the admin page, enter "Wrapperr Customization", and set "Maximum length of top lists" to 0, it should display all the albums listened to. 😁

**Comment by DoomTroopa84** [comment]
Thanks,

For some reason I can only see that option if I use edge as opposed to
firefox.

But works exactly how I wanted, any idea on what the tag I should put in
the header for that section to say the total number of albums AKA
audiobooks? {album_count} does not appear to work and my poor understanding
of tatulli api calls means I have no idea what to try.

Also is there wa y to filter out anything that was listened to for less
than say 10-15mins or ideally only list albums that were completed, similar
to how the movie section works?

**Comment by DoomTroopa84** [comment]
> Hey, thanks for trying out Wrapperr!
> 
>     * Allowing users to see more than the top 10 is something I can implement as a Wrapperr Customization feature, so thank you for the suggestion.
> 
>     * Posters/art is a good idea, and already suggested ([[FR] Add a poster for each entry in the tops #12](https://github.com/aunefyren/wrapperr/issues/12)), but I need a good way to implement them into the front end. I'll take some time to decide where to pull the assets from and how to display them correctly. The general look and mobile-friendly UI need to be preserved.
> 
>     * Newsletter/e-mail integration has also been suggested ([Send Email #6](https://github.com/aunefyren/wrapperr/issues/6)), and could be a great addition to the project. This could take some time to do correctly, but as you mentioned, creating URLs for users is an alternative. Most of this functionality is already implemented so it could function as a placeholder.
> 
>     * I'll take a look at the tag you mentioned and make sure it functions as it should. They were created quite quickly and should absolutely be documented properly.
> 
> 
> Thank you for your suggestions and feel free to ask if I can help with anything.

Hey sorry for the silly questions, but to make the URLs accessible for users, how do I do that? I assume one way is to open the port on the router but would prefer not to do that, I have a deidcated url dns for my nas, is it just appended to that?

One alternative would be for me to go and generate the the outputs, save them, then attach them to a end of year newsletter, can tautulli call wrapper to generate the page? that would remove the need for email integration from wrapper and just leverage tautuulli newsletter

**Comment by aunefyren** [comment]
Hi!

> Thanks, For some reason I can only see that option if I use edge as opposed to firefox. 

This is most likely your browser caching the previous version of Wrapperr. Clear your browser data or wait for the information to expire.

> {album_count} does not appear to work

I looked and there is currently no ` {album_count}` tag. The only ones available are the ones that appear by default when setting up Wrapperr. I am planning on expanding this and documenting them.

> filter out anything that was listened to for less
than say 10-15mins or ideally only list albums that were completed, similar
to how the movie section works?

This is currently not possible, but definitely, something that could be implemented. Not sure exactly how it should be implemented without being needlessly complicated, however. A minute threshold would be different for different media, so a completion option with a percentage variable is probably preferred.

>  make the URLs accessible for users, how do I do that?

There are multiple ways to do this. I understand not wanting to port forward. It is possible to set up a Cloudflare Argo tunnel, which I found especially easy when used with Docker. You could also create a VPN tunnel and access the application through that IP, or point a domain to it. 

> I have a deidcated url dns for my nas, is it just appended to that?

If you have a local DNS, only people on your network can reach services using that DNS. 

> can tautulli call wrapper to generate the page? that would remove the need for email integration from wrapper and just leverage tautuulli newsletter

The plan is to allow an admin to generate the URL for its users, which would allow the admin to extract the HTML and JS from the URL if desired. It is then possible to place this into an e-mail, but I have no clue how to do this, unfortunately. An e-mail feature is also planned but could take some time.
