### ISSUE TITLE
List of possible {xxxxxxx} we can use?

### ISSUE THREAD

**Issue by ctrlaltd1337ed** [aunefyren/wrapperr#43]
Apologies if this is already available and I've missed it.

Looking for an active list of all types or {movie}, {name}, etc that we can use. Was hoping to change the Plex username to the Tautulli name I've set instead for users after Plex force changed everyone's to a weird formula in the last year.

**Comment by aunefyren** [comment]
Hi! No, currently there is no documentation on this. The only options are those selected by default as they have been made by necessity.

The solution should be fixed up a bit and documented. Thank you for your input 😁

**Comment by aunefyren** [comment]
Fixed in v3.1.5.
