### ISSUE TITLE
Config Not Persisting

### ISSUE THREAD

**Issue by MatthewT1** [aunefyren/wrapperr#44]
Hello! 

I'm trying to setup a new Docker container for this program(I had it running as a PHP app in Nginx last year), but I'm running into some issues. 

I'm running the container on a Synology NAS - the issue I'm running into is that the config seems to overwrite itself, and I'm also having intermittent issues logging in. I can usually create an admin account after creating a new container, but then if I try to log into it I keep getting an auth error unless I clear my browser's cache a few times. 

 I confirmed the permissions are correct(and ran it as root temporarily to rule that out), tried with the networking on the host, and also tried passing through the port directly - for some reason it seems like its creating a ton of .replaced files in the volume but something is going haywire with it actually committing and using the new info. 

These are the files I'm seeing in the mounted volume:
![container files](https://user-images.githubusercontent.com/5216489/204942720-16796bb9-4409-4ca7-9350-56e186be7054.png)

And [this](https://github.com/aunefyren/wrapperr/files/10128449/wrapperr.2.log) should be the log - this is from a fresh install where I'd tried to make a new admin and configure Tautillu. 

One thing to mention - I do have PiHole running on my network and its strict on blocking stuff, so if there are external dependencies I might need to allow their domains. 

Any and all help would be appreciated, I'm not really sure what the issue could be at this point. I have managed to get it to work and show my own stats once, but when I checked the settings afterwards everything was null again.

**Comment by aunefyren** [comment]
Mmm, I think this is related to configuration file parsing and saving. The `.replaced` files occur when Wrapperr fails to parse the configuration file and replaces it with a fresh one. This in turn replaces your private key, which encrypts your login session tokens, meaning you have to re-log for each new config.

Just a few question to rule out confusions:

- Are you running v3.1.0?
- Are you using the official Docker image?
- If you let Wrapperr replace the configuration file, and restart Wrapperr, does it replace it again? Essentially meaning an infinite loop.
- Could you share what the configuration file looks like? Either a replaced and/or fresh one. Just replace/redact any content which seems confidential.

**Comment by aunefyren** [comment]
> Sure, I attached everything - I cleared out the files, restarted the container then setup a new admin and added fake Tautillui info. I then restarted the container and refreshed until it let me login and all the settings were wiped.

You managed to include some confidential information, such as your hashed password in the `admin.json` 😅

What is weird is that I managed to start up Wrapperr with all of those configuration files. So their overall structure/format is not configured wrong. Unless there is some OS/Platform related caveat I haven't taken into consideration, but it's Docker, it should work. 

Normally in these situations read/write permissions are to blame, but considering the container is able to rename the configuration files and create new ones, maybe not. The only error given by Wrapperr is "EOF" which doesn't really tell much, but it is related to reading/parsing the file. 

> EOF - Error is raised when one of the built-in functions hits an end-of-file condition (EOF) without reading any data.

Either way, I'm going to try to optimize Wrapperrs approach to reading files.

**Comment by scottruzal** [comment]
Having the same issue as above on 3.1.0. See below for container log and logfile text. Seems to be happening over and over with multiple replaced config.json files appearing in my config folder.

2022/11/30 16:13:28 Failed to parse config file. Trying legacy format. Error: json: cannot unmarshal object into Go struct field WrapperrConfig.tautulli_config of type []models.TautulliConfig

2022/12/02 11:50:42 Failed to parse config file. Trying legacy format. Error: EOF
2022/12/02 11:50:42 Failed to parse config file as legacy. Replacing, but saving backup. Error: EOF
2022/12/02 11:50:42 Old config file saved to '/app/config/config.json.3f7f81ed-9a3a-41ce-a9e2-294396567c6b.replaced'.

**Comment by aunefyren** [comment]
@scottruzal & @MatthewT1 

I rewrote the file writer/reader logic, it was already in need of some love. I also squashed some bugs along the way. It is kind of hard to help you guys, as I can't replicate the issue on my system but I made a new docker image `aunefyren/wrapperr:beta`. Could you guys try it out and check if the problem still persists?

@scottruzal, not sure if your are on Docker as well?

What OS are you guys running on?

**Comment by MatthewT1** [comment]
Thanks! I'm trying it out now and will let you know. 

I'm on Synology's OS , I think its a heavily customized fork of Debian.  I'm on 6.2.4-25556 Update 6.

**Comment by MatthewT1** [comment]
Alright the config issue is fixed! Thank you 😄

**Comment by scottruzal** [comment]
I have the same set-up running Docker on Synology OS. Just redeployed on the beta image and it appears to be working now. Thank you!!

**Comment by aunefyren** [comment]
Great to hear, thank you both for testing. I just need to finish up and test some more and then the changes will be available in v3.1.1 😁

**Comment by aunefyren** [comment]
Added in v3.1.1
