### ISSUE TITLE
Added in v3.1.0 😁

### ISSUE THREAD

**Issue by shutchi2** [aunefyren/wrapperr#45]
Added in v3.1.0 😁

_Originally posted by @aunefyren in https://github.com/aunefyren/wrapperr/issues/33#issuecomment-1331164021_
      
Awesome, works great, can I throw some money your way??

**Comment by aunefyren** [comment]
> ```
>     Added in v3.1.0 😁
> ```
> 
> _Originally posted by @aunefyren in [#33 (comment)](https://github.com/aunefyren/wrapperr/issues/33#issuecomment-1331164021)_
> 
> Awesome, works great, can I throw some money your way??

Haha, that's very kind of you! I probably should set up a "buy me coffee" button or something. For now, your gratitude is more than satesfactory ❤️
