### ISSUE TITLE
Reverse Proxy with subfolder not working (API response cant be parsed, Admin interface not working)

### ISSUE THREAD

**Issue by AmansRevenger** [aunefyren/wrapperr#46]
my nginx proxy conf:

```
location ^~ /wrapperr/ {

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host  $http_host;
        proxy_set_header Host              $http_host;
        proxy_pass                         http://192.168.1.16:8282/;
}
```

my relevant wrapper config:

```
	"wrapperr_version": "v3.1.0",
	"timezone": "Europe/Berlin",
	"application_name": "wrapperr",
	"application_url": "my-domain.com",
	"use_cache": true,
	"use_logs": true,
	"wrapperr_root": "wrapperr",
	"wrapperr_port": 8282,
```

Plex Auth doesnt work because it tries to 

```
index.js:253          POST https://192.168.1.16/api/validate/plex-auth 404
```

instead of  https://192.168.1.16/wrapperr/api/validate/plex-auth

![image](https://user-images.githubusercontent.com/18306225/205270964-22e75732-f07a-4260-aa96-006f26f98ac4.png)

same for the whole admin interface:

![image](https://user-images.githubusercontent.com/18306225/205270857-847f3d43-9e3a-4776-9773-03b41870e6c3.png)

```
POST https://192.168.1.16/api/get/wrapperr-version 404
```

as far as I can tell from main.go, you are not using your read-im `WrapperrRoot` var anywhere and all your api calls are hardcoded via the go router.

https://github.com/aunefyren/wrapperr/blob/main/main.go#L121

I think this could be fixed in this line but I cant test it currently sadly.

**Comment by aunefyren** [comment]
Thank you for your detailed issue! 

You are absolutely right, the `WrapperrRoot` parameter is added to the config, but not used yet. Fixing it in the backend should be simple. The line you sent, and some additional ones would have to be altered to take it into consideration. 

I haven't tested it yet, but the front end might be a bit more work. All API calls must be altered and tested to connect to the correct backend URL.

**Comment by aunefyren** [comment]
Added in v3.1.1
