### ISSUE TITLE
[proposal of PR] Docker/GHCR Image CI

### ISSUE THREAD

**Issue by mchangrh** [aunefyren/wrapperr#47]
Would you be interested in a PR to add Docker/ GHCR images on release?

**Comment by aunefyren** [comment]
Hei, would does Docker/ GHCR images entail? Do you mean an automated GitHub workflow that generates Docker images based on GitHub releases?

**Comment by mchangrh** [comment]
Yes, exactly that. Docker and/or GitHub container images on release and/or commits to a different image tag

**Comment by aunefyren** [comment]
That would be great!

**Comment by aunefyren** [comment]
I think I managed to figure out some GitHub actions that are suitable.
