### ISSUE TITLE
"Failed to reach Tautulli Server" Error Message Detail

### ISSUE THREAD

**Issue by sleepyh34d** [aunefyren/wrapperr#48]
Adding more detail to why Wrapperr has failed to connect to Tautulli server would be great. I am unable to diagnose a reason as to why I am unable to connect to a local instance of Tautulli otherwise.

**Comment by aunefyren** [comment]
Agreed, better logs and API responses are needed, especially for connection attempts.

Thank you

**Comment by aunefyren** [comment]
Added in v3.1.2
