### ISSUE TITLE
Sharing and Managed Users

### ISSUE THREAD

**Issue by dpeet** [aunefyren/wrapperr#49]
Hey @aunefyren!  Saw your post on reddit and had to spin up my own instance, this is great!

I ran into the issue of not being able to see a managed user.  I saw your suggestion to turn off plex auth, which worked but then I couldn't create a shareable URL... is there a way to have both?

Thanks!

**Comment by aunefyren** [comment]
Yeah, currently the shareable URL utilizes Plex Auth details to function, it doesn't really have to. I should add an alternative flow for non-Auth statistics.

**Comment by sandronidi** [comment]
+1 for this enhancement

**Comment by aunefyren** [comment]
Fixed in v3.1.5.

**Comment by WillPresley** [comment]
> Fixed in v3.1.5.

Seems like the version number got messed up on this latest release. It's now 1.3.5 instead of (the likely) 3.1.5. Just a heads up, nothing seems broken!

**Comment by aunefyren** [comment]
> > Fixed in v3.1.5.
> 
> Seems like the version number got messed up on this latest release. It's now 1.3.5 instead of (the likely) 3.1.5. Just a heads up, nothing seems broken!

Oh god, thank you for telling me! 😅
