### ISSUE TITLE
Most watched episode bug?

### ISSUE THREAD

**Issue by JoshTheBlack** [aunefyren/wrapperr#50]
My wrap shows I've watched an episode of tv 15 times for a total of 11h9m.  I checked Tautulli and there is only one play logged.

Not sure what could be causing it.

![image](https://user-images.githubusercontent.com/15058509/206564747-860c7946-6d41-44ed-9de1-404fb376e1cd.png)
![Screenshot from 2022-12-08 15-45-47](https://user-images.githubusercontent.com/15058509/206564890-bb6673af-c418-4d17-b674-e4a02af431b0.png)

**Comment by ZAKanoff** [comment]
It seems like it just goes off of the episode name. My most watched episode is Pilot from Yellowjackets, and it says I watched four times, but I actually watched four different episodes name Pilot from four different shows.

**Comment by dancurranjr** [comment]
RECEIVED is misspelled too

**Comment by aunefyren** [comment]
I think the previous PHP API build was more thorough, but the current version is less useful. It should compare episode number, season number, series title, and series year. I will fix this for the next release. 

Thank you

**Comment by aunefyren** [comment]
Added in v3.1.2
