### ISSUE TITLE
Working behind haproxy

### ISSUE THREAD

**Issue by secrdrew** [aunefyren/wrapperr#52]
I want to make wrapperr available to my users.  I have set everything up in haproxy. However, when I try to browse to my URL I get a 503 Service unavailable error.

I am wondering if I am missing something that is preventing me from getting it working.  I have multiple other services available via HAproxy.

Thanks for your help.

**Comment by aunefyren** [comment]
Hey, good question. I think I need a few more details to diagnose this issue. 

- Can you share your proxy config?
- Are you sharing the service using a domain/subdomain/IP or a subfolder/URL base? 
- Can you reach Wrapperr yourself using the connection details HaProxy utilizes for the proxy?

**Comment by secrdrew** [comment]
- I will get you the proxy config if I can figure it out.  I am using HAproxy in opnsense.
- I am sharing it with subfolder/url base.   stats.mydomain.com
- Yes I can get to wrapper using the local IP:port

**Comment by secrdrew** [comment]
Here is my config.

[https://pastebin.com/bTc9UJZn](url)

**Comment by aunefyren** [comment]
> * I am sharing it with subfolder/url base.   stats.mydomain.com

So you are using a subfolder/url base as well as the `stats` subdomain? The latest release is quite strict and requires a trailing slash in the URL.

Like this `stats.mydomain.com/mycoolbase/`.

**Comment by secrdrew** [comment]
Sorry no.  I am just using the subdomain.  So it is just stats.mydomain.com.

**Comment by aunefyren** [comment]
Mmm, I am sorry but I am not sure why you are having trouble using HaProxy. I haven't used it myself and everything seems to be correct. If the proxy can reach Wrapperr on 10.20.50.16:8282  then it should work.

**Comment by mrjohnpoz** [comment]
I just set this up for my users, and I am behind haproxy running on pfsense - had zero issues setting it up.  Clicky clicky and up and running. 

I just setup a frontend on my public IP on port 44301 (added firewall rule to allow that port), using a acme cert I setup using ssl offload, and the backend sends it to my nas that is running the docker to the nas IP 192.168.9.10 on port 8282
