### ISSUE TITLE
No ARM Docker build available

### ISSUE THREAD

**Issue by Weavus** [aunefyren/wrapperr#55]
Any plans to offer ARM builds of the Docker image? Currently only seems to be AMD64 being built.

[https://docs.docker.com/build/building/multi-platform/](url)

**Comment by aunefyren** [comment]
Seems wise. I suppose it would just need to expand on an ARM Docker image

**Comment by mchangrh** [comment]
I'm currently working on a PR for #47 that includes ARM64
