### ISSUE TITLE
Wrapperr is not configured

### ISSUE THREAD

**Issue by ctrlaltd1337ed** [aunefyren/wrapperr#57]
I've now set this thing up 3 times on Unraid and whenever someone logs into it and gets their stats, it unconfigures itself.

Running on Unraid, using Wrapper v3.1.1.

Edit: Ok, it looks like Wrapper was creating config.json.replaced files, and I just needed to make the oldest one the main config.json and it worked. Will report back if it happens again.

**Comment by aunefyren** [comment]
> it worked

Alrighty, good job
