### ISSUE TITLE
Ability to view who unwrapped or not

### ISSUE THREAD

**Issue by PierreDurrr** [aunefyren/wrapperr#60]
As per title, is It possible or would it be possible to be given a list of all plex users of a server and see who unwrapped and who didn't ?
Bonus point if able to send a remind mail.

**Comment by aunefyren** [comment]
Good idea. I am planning some sort of user menu anyway since another requested feature is to e-mail/export users' statistics from the admin panel.

**Comment by aunefyren** [comment]
Fixed in v3.2.0.
