### ISSUE TITLE
No version for raspberry pi

### ISSUE THREAD

**Issue by Rocknrolldoggie** [aunefyren/wrapperr#62]
Docker image won't work on a raspberry pi and other options would be wrong format. Any plans to make accessible to run on a pi ?

**Comment by dewmguy** [comment]
did you use the arm64 version or the amd64 version

**Comment by Rocknrolldoggie** [comment]
Hi. I tried both arm & amd as well as docker image

**Comment by aunefyren** [comment]
I am going to need some advice/help if I am going to make that work.

If my understanding is correct, some Raspberry Pi's require an amd/v7 Docker image to function. I added that to the GitHub release action to generate one, but it failed stating"apk update... did not complete successfully exec... format error". The only troubleshooting I could find was someone stating that the base-image for the Dockerfile must be compatible with arm/v7, but I am unsure on how to resolve this. I attempted to change the base image away from Alpine, but it did not work.

Anyone know anything that could help?

**Comment by Rocknrolldoggie** [comment]
Hi aunefyren & thanks for the reply, I am surprised you have never had this before I see a few people using pi as servers. Mine is a 3b+ which like many uses the armv7 base.

**Comment by aunefyren** [comment]
> Hi aunefyren & thanks for the reply, I am surprised you have never had this before I see a few people using pi as servers. Mine is a 3b+ which like many uses the armv7 base.

@Rocknrolldoggie, are you able to confirm if the new Wrapper Beta image works with the armv7 base?

`docker pull ghcr.io/aunefyren/wrapperr:beta`

**Comment by Rocknrolldoggie** [comment]
Hi Aunefryen. I only saw your reply a short while ago time difference I'm sure. You sir are an absolute genius it is WORKING. Stable enough for me to post to a few pi groups ?

**Comment by aunefyren** [comment]
> Hi Aunefryen. I only saw your reply a short while ago time difference I'm sure. You sir are an absolute genius it is WORKING. Stable enough for me to post to a few pi groups ?

Awesome! I had to change up some GitHub Actions to get it to work.

I have a new release coming up soon and I would probably wait until then, as the beta tag is pretty unstable. I will close this issue on release so you will be alerted. Thank you for contributing to the project.

**Comment by Rocknrolldoggie** [comment]
>
Hi Aunefryen. Ok all set up & working bar to things 
1. I am getting films watched this month in the stats (not sure if this is correct)
2.  All the top users except for me aren't on my server.

**Comment by aunefyren** [comment]
> > 
> 
> Hi Aunefryen. Ok all set up & working bar to things
> 
>     1. I am getting films watched this month in the stats (not sure if this is correct)
> 
>     2. All the top users except for me aren't on my server.

Hi, I am not sure if I am reading your issues correctly. Have you configured Wrapperr to your liking using the admin page? If any issues arise or you need more help please create a new unrelated issue and I'll be happy to assist you.

**Comment by Rocknrolldoggie** [comment]
24 hours later beta working perfectly and I have been going in and out. Good job.

**Comment by Rocknrolldoggie** [comment]
Got you. Thanks again.
