### ISSUE TITLE
"API response can't be parsed" - When accessing a 'share' link

### ISSUE THREAD

**Issue by muppet3000** [aunefyren/wrapperr#63]
I've just setup Wrapperr after setting up Tautulli earlier this week (with the intention of using it at the end of the year for a wrap-up.

I've got the whole system up and running nicely. However, when I try and access a 'share' link I'm presented with this page:
![image](https://user-images.githubusercontent.com/10612068/210661141-8de068d9-fa1f-4882-898b-d1207a64ddc0.png)

There's nothing appearing in the logs (in terms of errors): 
![image](https://user-images.githubusercontent.com/10612068/210661402-e1ea6531-798c-4fe4-ab80-3b8219e688a3.png)

I'm running using the docker container and I get the same issue whether I access it directly on the host or from via my reverse proxy.

Is there anything I can do to provide further logging to help debug? I'm not even sure if I'll use this feature but it would be good to have it working.

**Comment by muppet3000** [comment]
More info: The URL seems to be made up of a combination of the user_id and the hash from the configuration files.
https://<REDACTED>/wrapperr/?hash=2153917-228482c7-028a-40e2-a1f1-552abdd1c3ff

The first number after the hash seems to be the user_id, is that correct? Either way I've tried multiple different changes and it doesn't make a difference.

NOTE - I'm running wrapperr with a URL Base e.g. "wrapperr" is part of the URL (in case that's related in any way)

**Comment by muppet3000** [comment]
Further update: If I remove the base url "wrapperr" from the configuration then it works fine, I can't seem to get it to work with it in though.
Any help would be greatly appreciated, even though I have this configured and working with a reverse proxy all the above testing is done by hitting the host directly to make the debugging simpler.

**Comment by aunefyren** [comment]
Fixed in v3.1.3. Thank you for reporting!

**Comment by muppet3000** [comment]
Confirmed working - Thanks!
