### ISSUE TITLE
Top users not my users

### ISSUE THREAD

**Issue by Rocknrolldoggie** [aunefyren/wrapperr#64]
Hi Aunefyren. Strange issue that I cant find anything online about but sure I'm being stupid. My top 10 users has my Username (Rocknrolldoggie) correctly but all the others are not my shared users. I share with 5 family members & all on tautulli are listed correctly with their first names but in your program I have things like Summer Night & Wispy Dream (there are stats for all of them)

**Comment by aunefyren** [comment]
Hey, you are using the beta Docker image which includes a feature called `Obfuscate other usernames`. It can be disabled using the admin panel at `Wrapperr customization`.
