### ISSUE TITLE
Recommendations on how to get around "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by WingZeroh** [aunefyren/wrapperr#65]
Hello,

I have my Tautulli using a self-signed certificate pointing to my domain so that some scripts can execute without error. Now I am encountering an error with Wrapperr. I am unable to get past the setup for Tautulli because it is returning:

`"Failed to reach Tautulli server. Error: Get "https://192.168.x.x:8888/api/v2/?apikey=REDACTED&cmd=status": x509: certificate signed by unknown authority"`

Does anyone have any suggestions? Wrapperr seems pretty cool so I'd like to have it around. I did get it to work if I don't utilize Taultulli's self-signed certificate feature.

**Comment by aunefyren** [comment]
Does Tautulli and/or Wrapperr use docker containers? The container/machine running Wrapperr needs to trust the certificate authority which created the Tautulli-self-signed certificate, which is the server/container Tautulli is running in.
