### ISSUE TITLE
Stopped Opening Up and NO useful Logs

### ISSUE THREAD

**Issue by thorrrr** [aunefyren/wrapperr#66]
HI
I can no longer access the user interface locally or externally and no way to track why it has stopped working?
This stopped logging months ago !!!
[wrapped.log](https://github.com/aunefyren/wrapperr/files/11690423/wrapped.log)

**Comment by aunefyren** [comment]
Hey, appreciate you wanting to use Wrapperr but I need some more info if I am going to try to help you.

I am noticing only log messages from the PHP era of Wrapperr (v1.X.X and v2.X.X). My best guess is that you need to update your configuration to work with v3.X.X , for example, Wrapperr now automatically starts on port 8282. What does the console of Wrapperr say?

If that is not the issue I am going to need some more information, like operating system, running type (docker, built from source etc.), Wrapperr version, and a redacted version of configuration file.

**Comment by thorrrr** [comment]
I am on Log file enabled.
Running version v3.1.4.
Starting Wrapperr on port 8282.
Unraid Version: 6.11.5

![image](https://github.com/aunefyren/wrapperr/assets/8170673/fbd801b4-1578-478c-a555-d336aac73694)

**Comment by aunefyren** [comment]
There have been issues in the past with Unraid applications. I don't use Unraid and don't know how to contribute to the platform, so the integrations are user made and sometimes not correct.

The yellow text says the container port is `80`, unless you change it that is not correct. The container starts by default on port `8282`.

The yellow text says container path is `/mnt/user/appdata/plex-wrapped`, that is not correct. The container stores files in `/app/config`.

**Comment by thorrrr** [comment]
All my containers are stored in /mnt/user/appdata thats the correct way to set it up and it worked for a long time 

See config file https://docs.google.com/document/d/1A3OAKDLw-0sohyQjKTforIwwngPtyk4ED9jM6jV0KK4/edit?usp=sharing

**Comment by aunefyren** [comment]
Your image says the configured container path **within** the container is `/mnt/user/appdata/plex-wrapped`. That is what is mistaken. 

Same with the port. The port **within** the container needs to be configured to Wrapperr configured port, which you said is currently `8282`.

**Comment by thorrrr** [comment]
Sorry I have 28 containers all configured to same path all have worked for 5 plus years. You app has been running for 2 plus years why is it an error if it point to all you files?

**Comment by aunefyren** [comment]
I don't think you understand what I am saying.

> There have been issues in the past with Unraid applications. I don't use Unraid and don't know how to contribute to the platform, so the integrations are user made and sometimes not correct.

As I said here, you are using a user-made integration/configuration of this code for Unraid. It is not made by me and is probably deprecated. The settings within the integration are outdated. I don't know if you can update these settings as I did not make the integration.

**Comment by thorrrr** [comment]
OK cheers i will remove it from Unraid then sorry to bother you and thank you for your speedy response

**Comment by aunefyren** [comment]
No worries, thanks for checking out the project.

If you have documentation on how to contribute/edit Unraid applications feel free to provide it so I can make sure they stay up to date with the project.
