### ISSUE TITLE
Admin Page Basic Auth

### ISSUE THREAD

**Issue by kuantek** [aunefyren/wrapperr#67]
Is it possible for the admin page to utilize basic auth instead of a form login? I use Organizr SSO for all my media related services with Nginx and can pass the Authorization header after completing the auth_request to Organizr.

This may be a bit of a corner case and not a huge deal, so if it's dumb, feel free to close the issue.

**Comment by aunefyren** [comment]
Hi, not a bad idea. This would require some API rewrites, but this is due for an update anyway. Thanks for the suggestion.

**Comment by aunefyren** [comment]
Fixed in v3.2.0.
