### ISSUE TITLE
Grabbing Friendly name from Tautulli not working 

### ISSUE THREAD

**Issue by wbshaw** [aunefyren/wrapperr#68]
The APi call to Tautulli is not referencing the correct field to get the friendly name so it is always defaulting back to the username. 

https://github.com/aunefyren/wrapperr/blob/main/modules/tautulli.go - Line 129 > 130
`if body_reply.Response.Data[i].FriendlyName != "" {
				username = body_reply.Response.Data[i].FriendlyName`

Checking the API response for Tautulli for get_users the field name comes back as "friendly_name".

**Comment by aunefyren** [comment]
Mmm, that is odd. I get the friendly names myself. Are you able to do an API call to `http(s)://[YOUR-TAUTULLI]/api/v2/?apikey=[TAUTULLI_API-KEY]&cmd=get_users` and give med a redacted sample? Maybe Tautulli updated their API or something.

**Comment by wbshaw** [comment]
API response is here - looks to be the same as is in the code though:
 - One note - I'm only checking as the admin right now, before I release out to users, would that make a difference to how the name is rendered? 
 
`{"response": {"result": "success", "message": null, "data": [{"row_id": 1, "user_id": 0, "username": "Local", "friendly_name": "Local", "thumb": null, "email": null, "is_active": 1, "is_admin": 0, "is_home_user": null, "is_allow_sync": null, "is_restricted": null, "do_notify": 1, "keep_history": 1, "allow_guest": 0, "shared_libraries": [], "filter_all": null, "filter_movies": null, "filter_tv": null, "filter_music": null, "filter_photos": null}, {"row_id": 2, "user_id": *******, "username": "wbs****", "friendly_name": "Will Shaw", "thumb": "https://plex.tv/users/[******]", "email": "ws@email.com", "is_active": 1, "is_admin": 1, "is_home_user": 1, "is_allow_sync": 1, "is_restricted": 0, "do_notify": 0, "keep_history": 1, "allow_guest": 0, "shared_libraries": ["1", "3", "4", "5"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}, {"row_id": 3, "user_id": *******, "username": "cra****", "friendly_name": "Craig Smith", "thumb": "https://plex.tv/users/[******]", "email": "cs@email.com", "is_active": 1, "is_admin": 0, "is_home_user": 0, "is_allow_sync": 1, "is_restricted": 0, "do_notify": 0, "keep_history": 1, "allow_guest": 0, "shared_libraries": ["1", "5", "3"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}, {"row_id": 4, "user_id": *******, "username": "lotti****", "friendly_name": "Socks", "thumb": "https://plex.tv/users/[******]", "email": "ls@email.com", "is_active": 1, "is_admin": 0, "is_home_user": 0, "is_allow_sync": 1, "is_restricted": 0, "do_notify": 0, "keep_history": 1, "allow_guest": 1, "shared_libraries": ["1", "5", "3"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}, {"row_id": 5, "user_id": *******, "username": "Mal****", "friendly_name": "Malibu", "thumb": "https://plex.tv/users/[******]", "email": "ssm@email.com", "is_active": 1, "is_admin": 0, "is_home_user": 0, "is_allow_sync": 1, "is_restricted": 0, "do_notify": 0, "keep_history": 1, "allow_guest": 0, "shared_libraries": ["1", "5", "3"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}, {"row_id": 6, "user_id": *******, "username": "nxe***", "friendly_name": "Ellie & Dan", "thumb": "https://plex.tv/users/[******]", "email": "nx@email.com", "is_active": 1, "is_admin": 0, "is_home_user": 0, "is_allow_sync": 0, "is_restricted": 0, "do_notify": 0, "keep_history": 1, "allow_guest": 0, "shared_libraries": ["1", "5", "3"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}, {"row_id": 7, "user_id": *******, "username": "pet****", "friendly_name": "Pete Morley", "thumb": "https://plex.tv/users/[******]", "email": "pm@email.com", "is_active": 1, "is_admin": 0, "is_home_user": 0, "is_allow_sync": 1, "is_restricted": 0, "do_notify": 0, "keep_history": 1, "allow_guest": 1, "shared_libraries": ["1", "5", "3"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}, {"row_id": 8, "user_id": *******, "username": "shane****", "friendly_name": "Martin Jones", "thumb": "https://plex.tv/users/[******]", "email": "smj@email.com", "is_active": 1, "is_admin": 0, "is_home_user": 0, "is_allow_sync": 1, "is_restricted": 0, "do_notify": 0, "keep_history": 1, "allow_guest": 0, "shared_libraries": ["1", "5", "3"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}, {"row_id": 9, "user_id": *******, "username": "Strut*****", "friendly_name": "Simon Holmes", "thumb": "https://plex.tv/users/[******]", "email": "dsp@email.com", "is_active": 1, "is_admin": 0, "is_home_user": 0, "is_allow_sync": 0, "is_restricted": 0, "do_notify": 0, "keep_history": 1, "allow_guest": 0, "shared_libraries": ["1", "5", "3"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}, {"row_id": 10, "user_id": *******, "username": "subc***", "friendly_name": "Carl Bateson", "thumb": "https://plex.tv/users/[******]", "email": "ssct@email.com", "is_active": 1, "is_admin": 0, "is_home_user": 0, "is_allow_sync": 0, "is_restricted": 0, "do_notify": 0, "keep_history": 1, "allow_guest": 0, "shared_libraries": ["1", "5", "3"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}, {"row_id": 11, "user_id": *******, "username": "the****", "friendly_name": "Grumble", "thumb": "https://plex.tv/users/[******]", "email": "md@email.com", "is_active": 1, "is_admin": 0, "is_home_user": 0, "is_allow_sync": 0, "is_restricted": 0, "do_notify": 0, "keep_history": 1, "allow_guest": 0, "shared_libraries": ["1", "5", "3"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}, {"row_id": 12, "user_id": *******, "username": "mel****", "friendly_name": "Mel Aitken", "thumb": "https://plex.tv/users/[******]", "email": "ms@email.com", "is_active": 1, "is_admin": 0, "is_home_user": 0, "is_allow_sync": 1, "is_restricted": 0, "do_notify": 0, "keep_history": 1, "allow_guest": 0, "shared_libraries": ["1", "5", "3"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}, {"row_id": 13, "user_id": *******, "username": "emma****", "friendly_name": "Emmah Arnold-Smith", "thumb": "https://plex.tv/users/[******]", "email": "ehs@email.com", "is_active": 1, "is_admin": 0, "is_home_user": 0, "is_allow_sync": 1, "is_restricted": 0, "do_notify": 0, "keep_history": 1, "allow_guest": 0, "shared_libraries": ["1", "5", "3"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}, {"row_id": 14, "user_id": *******, "username": "pag****", "friendly_name": "Emma Pagent", "thumb": "https://plex.tv/users/[******]", "email": "pel@email.com", "is_active": 1, "is_admin": 0, "is_home_user": 0, "is_allow_sync": 1, "is_restricted": 0, "do_notify": 0, "keep_history": 1, "allow_guest": 0, "shared_libraries": ["1", "5", "3"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}, {"row_id": 15, "user_id": *******, "username": "Emi****", "friendly_name": "Emily", "thumb": "https://plex.tv/users/[******]", "email": "", "is_active": 1, "is_admin": 0, "is_home_user": 1, "is_allow_sync": 0, "is_restricted": 1, "do_notify": 1, "keep_history": 1, "allow_guest": 0, "shared_libraries": ["1", "3"], "filter_all": "", "filter_movies": "contentRating=G%2CTV-G%2CTV-Y%2Cgb%2FUc%2Cgb%2FU%2CUK%3A+Uc%2CUK%3A+U%2Cde%2F0%2CFSK+0%2CAb+0+Jahren%2Cau%2FG%2Cca%2FG%2Cfr%2FTous+publics%2Cfr%2FU%2Cbr%2FL%2Cbr%2FLivre%2Cch%2F0%2Cnl%2FAL%2Ces%2FAPTA%2Cdk%2FA%2Ckr%2FA%2Cse%2FBtl%2CCSM+3%2CCSM+4%2CCSM+5%2C0%2C0%2B%2C2%2C3%2C4%2C5%2CUS%2FG%2CUS%2FTV-G%2CUS%2FTV-Y", "filter_tv": "contentRating=G%2CTV-G%2CTV-Y%2Cgb%2FUc%2Cgb%2FU%2CUK%3A+Uc%2CUK%3A+U%2Cde%2F0%2CFSK+0%2CAb+0+Jahren%2Cau%2FG%2Cca%2FG%2Cfr%2FTous+publics%2Cfr%2FU%2Cbr%2FL%2Cbr%2FLivre%2Cch%2F0%2Cnl%2FAL%2Ces%2FAPTA%2Cdk%2FA%2Ckr%2FA%2Cse%2FBtl%2CCSM+3%2CCSM+4%2CCSM+5%2C0%2C0%2B%2C2%2C3%2C4%2C5%2CUS%2FG%2CUS%2FTV-G%2CUS%2FTV-Y", "filter_music": "", "filter_photos": ""}, {"row_id": 16, "user_id": *******, "username": "Haz***", "friendly_name": "Hazel", "thumb": "https://plex.tv/users/[******]", "email": "", "is_active": 1, "is_admin": 0, "is_home_user": 1, "is_allow_sync": 0, "is_restricted": 1, "do_notify": 1, "keep_history": 1, "allow_guest": 0, "shared_libraries": ["1", "3"], "filter_all": "", "filter_movies": "", "filter_tv": "", "filter_music": "", "filter_photos": ""}]}}`

**Comment by wbshaw** [comment]
In the 'top users' section it does display my friendly name correctly I've noticed, it's just at the top of the stats page where it is showing "Hey there [myusername]".

**Comment by aunefyren** [comment]
Ahh, thank you, your note the gave me the clue. If I found the username from the Plex Auth login, I didn't bother to get the friendly name for the requester. Fixed in beta/the upcoming release.

**Comment by wbshaw** [comment]
Awesome! Thanks you.

**Comment by wbshaw** [comment]
Just checked with the latest changes you made and all working great now!

**Comment by aunefyren** [comment]
Fixed in v3.1.5.
