### ISSUE TITLE
Docker image doesn't match released version

### ISSUE THREAD

**Issue by muppet3000** [aunefyren/wrapperr#71]
It looks like the docker image never got re-published when you fixed the incorrect version tag. Therefore the docker tag for the latest release is still `v1.3.5` instead of `v3.1.5`.
Any chance of a re-release/re-tag to allow my OCD to cope with the 'upgrade' not going backwards 2 major versions?

**Comment by aunefyren** [comment]
I feel you, I have a release so I can fix it by releasing it ;)

**Comment by aunefyren** [comment]
Fixed in v3.2.0 ;)

**Comment by muppet3000** [comment]
<immediately pulls and runs>

Thank you
