### ISSUE TITLE
Wrapperr stop working after latest update

### ISSUE THREAD

**Issue by daurpam** [aunefyren/wrapperr#73]
The app was working without issues for the last year. After update to the 3.2.0 version, there is nothing to unwrap. Every user that try to use get the message "true" downside the main buttons:
![image](https://github.com/aunefyren/wrapperr/assets/18077653/480f1209-9513-4d12-90fe-0cbc5d6b471f)

I've change the period for the unwrap info, but nothing changes. This is the log result

[wrapperr.log](https://github.com/aunefyren/wrapperr/files/13326354/wrapperr.log)

Thanks for your work!

**Comment by aunefyren** [comment]
Hey, sorry for the late reply. 

Are you able to re-test on v3.2.1? The last version had a couple of issues.

**Comment by daurpam** [comment]
Hi @aunefyren, after update to the latest image, seems that it works perfectly. Thank you so much 

Ready for the next wrapper of the end of 2023! 😉
