### ISSUE TITLE
User is not active.

### ISSUE THREAD

**Issue by Jomack16** [aunefyren/wrapperr#74]
When configured with multiple tautulli instances only the users in the topmost configured tautulli instance are able to 'unwrap'.
I have 4 tautulli instances configured in the admin settings. (tautulli1, tautulli2, tautulli3, tautulli4)
User from tautulli1 can 'unwrap', but users from the other 3 receive 'User is not active.' message.
When I remove tautulli1 from the configuration, now users from tautulli2 can unwrap.

I am currently using the beta tag for the docker container.
docker create \
  --name=plexwrapper \
  --hostname=plexwrapper \
  -e TZ=America/Chicago \
  -p 8282:8282 \
  -v /opt/DockerAppdata/plexwrapper:/app/config \
  --restart=unless-stopped \
  ghcr.io/aunefyren/wrapperr:beta
  
[wrapper logs.zip](https://github.com/aunefyren/wrapperr/files/13354257/wrapper.logs.zip)

**Comment by aunefyren** [comment]
Hey, thank you for the detailed issue. 

I think this should be fixed now, as the user aggregation now takes into account that the user could exist on multiple Tautulli servers. Active status on any Tautulli server will make Wrapperr assume the user is active.

It is hard for me to replicate this issue, as I have one Tautulli server, therefore this fix has not been released yet, are you able to test the `main` branch by compiling it with:
```
$ go build .
```

or the `beta` Docker image: `ghcr.io/aunefyren/wrapperr:beta`?

Make sure to entire refresh the page/try an incognito window to make sure your browser is not caching any old data.

**Comment by Jomack16** [comment]
I pulled the latest :beta image, and it is working!
I am able to 'unwrap' with a user from each tautulli instance.
Thank you so much! This is like a Christmas gift!

**Comment by aunefyren** [comment]
Fixed in v3.2.1.

Thank you so much for the kind words!
