### ISSUE TITLE
UI: Adding a Tautulli server, clears the previous form

### ISSUE THREAD

**Issue by Dr-Blank** [aunefyren/wrapperr#78]
During the first-time setup

I have no servers added and setting up wrapperr for the first time.

When filling out tautulli server details, i accidentally clicked add new server instead of save, and this cleared the first server details.

Once saved and adding a new tautulli server, this does not happen.

**Comment by aunefyren** [comment]
Thank you for submitting an issue, I'll have a look!

**Comment by aunefyren** [comment]
Fixed in v3.2.3.
