### ISSUE TITLE
Run for the other Plex managed users

### ISSUE THREAD

**Issue by modem** [aunefyren/wrapperr#80]
It seems I can only run Wrapperr for the Plex user (with Plex account) but I can't find a way to run for the my other managed users, although Wrapperr knows who they are as they show on the statistics results.

I've seen in another topic that if we disable Plex loging we are promped to fill the other users. Can you provide more details? On the Wrapperr main page I only see the **Sign in using Plex** button and nothing else.

![image](https://github.com/aunefyren/wrapperr/assets/62859/62dc2a6a-ba33-41de-9ede-1add12acabc8)

If I login using Plex, I then have the **Unwrap** button and a **Sign Out** button.
![image](https://github.com/aunefyren/wrapperr/assets/62859/e0f6bbca-c2be-499b-9131-d3c26ff5ceea)

I'm running the latest v3.2.2, and tested on Firefox and Chrome (something could be missing on one browser).

**Comment by aunefyren** [comment]
Hey,

to be able to do managed users you need to disable Plex Auth in the admin menu. 

Meaning `Admin Menu` -> `Wrapperr settings` -> `Use Plex Auth`. 

This is the menu where the administrator previously added the Tautulli servers and so on. This should probably be explained in the documentation, I'll make a note of it.

**Comment by modem** [comment]
That was it, I looked so many times to that page and always missed that option.

Thanks!
