### ISSUE TITLE
can't configure wrapperr with a base url

### ISSUE THREAD

**Issue by BasO12** [aunefyren/wrapperr#82]
I am currently trying to set up Wrapper with a base url like this:
![image](https://github.com/aunefyren/wrapperr/assets/94169344/24e492bf-6e53-4518-9e91-27723a652082)
however when I do this, I get the error "unable to parse api" and I lose complete access to Wrapperr.
The request I see in the logs ends up looking like this:
![image](https://github.com/aunefyren/wrapperr/assets/94169344/3418a3d7-0943-4da3-ae06-192177866c73)

If I do not use the /wrapped url in nginx, it works flawlessly.
What am I doing wrong?

**Comment by aunefyren** [comment]
Hey, thanks for submitting an issue.

Have you restarted Wrapperr after the change? Also what is your Nginx config? You use `/wrapperr` in the screenshot.

**Comment by BasO12** [comment]
Hello,
Thanks for the response, I used these entries as an example. I have been trying it with 'wrapped' in nginx:
![image](https://github.com/aunefyren/wrapperr/assets/94169344/5a792fa5-8eba-49a5-959a-b5ad7b602827)
when I use this exact config with just '/' as location and no url base, it works just fine.
Restarting my docker container does not help sadly.

**Comment by aunefyren** [comment]
Are you trying to map `wrapper-ip/wrapperr` to `nginx-ip/wrapped`. In your first screenshot the base is `/wrapperr`. 

Also, is that Nginx config correct? Wouldn't be something like this?

```
location /wrapped {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass http://[WRAPPERR-IP]:8000/wrapped;
}

```

**Comment by BasO12** [comment]
Oh my god, the '/wrapped' at the end of the proxy_pass seems to have done the trick.
Thanks a lot!

**Comment by aunefyren** [comment]
No worries
