### ISSUE TITLE
Same Album Name, Different Artist

### ISSUE THREAD

**Issue by seannuh** [aunefyren/wrapperr#84]
I could be doing something wrong, but I was trying to figure out why it reported so much of Unknown Mortal Orchestra's latest album V because I only listened to that once, but it came in as my top album. However, I have quite a few albums named V by other artists and I did listen to those more (Follakzoid, The Horrors, Budos Band). I looked through my Tautulli stats and added up the plays, and it seemed that the report from Wrapperr was including all of those albums as the Unknown Mortal Orchestra album. Anyway around this?

And thank you so much for this tool, it's really incredible.

**Comment by aunefyren** [comment]
Hey, thanks for submitting an issue and the compliment!

I was going to say that is odd, as track and album matching is done using multiple attributes, such as artist name. But, looking at the code, apparently it didn't. It was just track/album name and release date/year. I changed the code to also verify the artist name, which should make better matching. Nothing changed for my statistics, but perhaps they do for you.

**Comment by seannuh** [comment]
Oh great. Is there an update I need to apply first for this? I tried clearing the cache and running things again but didn't see any stats change either.

**Comment by aunefyren** [comment]
Yes, either use the `ghcr.io/aunefyren/wrapperr:beta` image if you are running Docker, download the main branch and compile, or wait for a new release here on GitHub.

**Comment by seannuh** [comment]
Ah got it, no Docker here so I'll wait. Thanks for such quick responses!!

**Comment by aunefyren** [comment]
Fixed in v3.2.3.

**Comment by seannuh** [comment]
Was just jumping in to say yes, it does look fixed now, thanks!!
