### ISSUE TITLE
Docker update drops config

### ISSUE THREAD

**Issue by cyberweasel** [aunefyren/wrapperr#94]
Hello,
I seem to have a problem whenever there is a new version and the docker container updates, it seems to drop my config and I have to go through setup again.  I saw something in the wiki about mapping a config folder.   Not sure if this is the fix or if there is something else I can do.  Thanks.

**Comment by aunefyren** [comment]
If you have not mapped the config file, or place it in a persistent Docker volume, it will be removed every time the container restarts.
