### ISSUE TITLE
Causing Tautulli to login loop

### ISSUE THREAD

**Issue by EtsuRah** [aunefyren/wrapperr#96]
I had Tautulli logged in when I ran the .exe (Windows 10 x64), went to go to the settings to get the API key during setup and it knocked me back to login. 

I chose "sign in with plex" selected my email and PW the page went as if it were loading then threw me back to the Tautulli sign in page endlessly. 

I opened another browser and Tautulli let me in. Once I ran the wrapperr.exe again the same thing happened on the other browser. It sent me to a sign in loop. 

Restarting the PC, exiting out of wrapperr, restarting the browser none of those worked. Even with Wrapperr not running I can no longer sign into Tautulli on any browser that was up when Wrapperr ran its executable.

To get it to work again I must completely purge the browser, but running Wrapperr causes it to happen again.

**Comment by aunefyren** [comment]
The web potion of Wrapperr does not send you to Tautulli in any way. The back end uses the API key to contact the Tautulli server and retrieve data.

Is the login-loop you are describing happen at the Tautulli web site? If so, he problem is most likely there. 

> To get it to work again I must completely purge the browser, but running Wrapperr causes it to happen again.

Are you running these servers on the same machine? Are they using the same port? Do you use any sort of reverse proxy?

**Comment by Tchuch0** [comment]
New user here and i cant get it connected to Tautulli and upon getting a fresh install on my unraid i also get a login loop after i open the wrapper on the browser. 
New browser all good in Tautulli until i also open wrapper, then same loop

**Comment by franchiceddhu** [comment]
Hey, that's funny, it's happening to me as well. Same exact method. Running tautulli from an incognito window solves the problem until I enter wrapper and log as admin (I can always reproduce it).

I'm running both wrapper and tautulli on the same Unraid server as Docker containers (tautulli comes from linuxserver's one, latest update). They don't use the same port (yet they're quite similar, something like 5656 and 5757). I use CloudFlare Zero Trust tunneling; using my domain to access tautulli works every time, but the login loop works if I use the local IP address to access the webUI. I'm trying to access tautulli from another machine with Chrome browser on Windows 11.

I can confirm that this issue can be reproduced even on a Chrome installation on another PC. I am at work, logged with a WireGuard VPN to my home network (via FritzBox), yet the same issue appears if I use the local IP address.

**Comment by aunefyren** [comment]
> but the login loop works if I use the local IP address to access the webUI. 

Where/how does the login loop happen? What does it look like? Would love a video.

**Comment by franchiceddhu** [comment]
> Where/how does the login loop happen? What does it look like? Would love a video.

Sorry if I answer only today - I was busy. Thanks for your support!

This is the video. I've started by opening a new Guest tab on my Chrome browser.

https://github.com/user-attachments/assets/0ccbc240-a5e8-453c-82fa-33f49ae673a2

As you can see, as long as I don't log into wrapper, Tautulli works fine and I can log without any problems. Once I've logged as admin in wrapper, then Tautulli says "there was an error communicating with your Plex server" and then I can't log in anymore. Same login loop happens if I choose Plex authentication.

I can log into Tautulli once again by opening a new incognito/guest window or by using a Cloudflare tunneled URL within my personal domain instead of the direct local IP address.

It is worth noting that this issue happened even before I compiled my Tautulli settings (IP; port and API) into my wrapper setup. It just seemed to trigger after I registered an admin account for the first time.

**Comment by JonnyWong16** [comment]
The Wrapper cookie has a white space that either needs to be URL encoded or double quoted.

`wrapperr-admin=Bearer%20abc123` or `wrapperr-admin="Bearer abc123"`

https://stackoverflow.com/a/6109881

The white space doesn't conform to RFC 6265 so when Tautulli is parsing cookies from the same origin it fails.

**Comment by wbshaw** [comment]
![image](https://github.com/user-attachments/assets/0d20f159-1aef-44fa-9720-ff2ec0bd0381)
Had a quick look and play to see if this was easy to sort. Made the changes shown in the image and compiled to a windows exe and tested logging in / out of both wrapperr and tautulli multiple times (after clearing the old cookies) and so far seems to be working fine.

**Comment by aunefyren** [comment]
I knew my URL encoding would one day come back to haunt me. Not sure how it causes this bug though.

v3.2.8 has the token URI encoded upon creation, hopefully that resolves this. Hope someone can try and recreate this issue.

**Comment by franchiceddhu** [comment]
Looks like for me it's working correctly. I can access Tautulli with Plex auth and it will stay connected even if I log into wrapper. Thanks a lot!

**Comment by aunefyren** [comment]
Wow, love to hear it. Thanks for the help people!
